name: cpd
channels:
  - clinicalgraphics
dependencies:
# run
  - python
  - matplotlib
  - numpy
  - pandas
  - scipy
  - future >=0.15,<0.16
  - jupyter >=1.0,<1.1
  - notebook >=4.0,<4.1
  - flake8 >=2.3,<2.4
  - flake8-future-import >=0.3.2,<0.4
  - pep8-naming >=0.3.3,<0.4
  - anaconda-client >=1.2.1,<1.3
  - pyyaml >=3.11,<3.12
  - jinja2 >=2.8,<2.9
  - invoke >=0.11.1,<0.12
  - six >=1.10,<1.11
# tests
  - pytest >=2.8.4,<2.9
  - mock >=1.3,<1.4
# docs
  - sphinx >=1.3.1,<1.4
  - numpydoc >=0.5,<0.6
  - recommonmark >=0.2,<0.3